### ISSUE TITLE
Can it be possible with WhatsApp Beta?

### ISSUE THREAD

**Issue by MarcusCorbacho** [Zigatronz/Windows-10-WhatsApp-to-Taskbar-Tray#1]
Tested and it work fine with WhatsApp from Microsoft Store. 
But on my system have both version installed: WhatsApp and WhatsApp Beta from Microsoft Store.

WhatsAppTray.exe  opened the WhatsApp 

Can it be used with Beta version ?

**Comment by Zigatronz** [comment]
The current version of this WhatsApp Tray can't be used for WhatsApp Beta since WhatsApp Beta used an 'Application Frame Host', the window GUI is different from the stable version. But I'll try it out for Whatsapp Beta.

**Comment by MarcusCorbacho** [comment]
This is exciting news. Glad to see this response, thanks. I use both of them: Regular and Beta.. But Beta for my personal account and the GUI is so much better then the regular. Regular is for work account. I was searching and looking for any way to keep both of then minimized to tray... I do not like web version (so much slow) and the only way to use both of then opened without problem is use from MS Store the two version: Beta and Regular.

**Comment by MarcusCorbacho** [comment]
![Captura de tela 2022-07-26 130758](https://user-images.githubusercontent.com/42424196/181056386-b3cc4ce7-d20d-4a7a-9a8c-a6abbec1e7f1.png)

Both process up and running...

**Comment by Zigatronz** [comment]
Hi, recently WhatsApp rolled out a UI update which they moved completely to 'Application Frame Host'. Now, the UI is unhideable. More details (here)[https://stackoverflow.com/questions/74001810]. But there's still a WhatsApp app that does not use 'Application Frame Host' and I'm going to work on it.
